=== Suong-Tran/HTTP-5203-Assignment2-SuongTran/tickets.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="tickets">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ticket" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" type="xs:string" />
                            <xs:element name="messages">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="message" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute name="id" type="userId" />
                                                        <xs:attribute name="date" type="xs:dateTime" />
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="ticketId" />
                        <xs:attribute name="status" type="ticketStatus" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="ticketStatus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ongoing" />
            <xs:enumeration value="resolved" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ticketId">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{4}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="userId">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{3}" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Suong-Tran/HTTP-5203-Assignment2-SuongTran/xml/tickets.xml
<?xml version="1.0" encoding="utf-8"?>
<tickets xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/tickets.xsd">
    <ticket id="00001" status="ongoing">
        <subject>No sounds on app</subject>
        <messages>
            <message id="00002" date="2021-05-21T12:20:50">Hi, I would like some helps please</message>
            <message id="00001" date="2021-05-21T12:25:00">Hello, how can I help?</message>
            <message id="00002" date="2021-05-21T12:30:50">There is no sounds from my app</message>
        </messages>
    </ticket>
    <ticket id="00002" status="ongoing">
        <subject>Please fix</subject>
        <messages>
            <message id="00002" date="2021-05-21T12:20:50">Hi, I would like some helps please</message>
            <message id="00001" date="2021-05-21T12:25:00">Hello, how can I help?</message>
            <message id="00002" date="2021-05-21T12:30:50">Thanks</message>
        </messages>
    </ticket>
    <ticket id="00003" status="ongoing">
        <subject>Would you kindly</subject>
        <messages>
            <message id="00003" date="2021-05-21T12:20:50">Hi, I would like some helps please</message>
            <message id="00001" date="2021-05-21T12:25:00">Hello, how can I help?</message>
            <message id="00003" date="2021-05-21T12:30:50">There is no sounds from my app</message>
        </messages>
    </ticket>
</tickets>
