=== Suong-Tran/HTTP-5203-Assignment2-SuongTran/users.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="id" type="userId" />
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="first" type="xs:string" />
                                        <xs:element name="middle" type="xs:string" minOccurs="0" />
                                        <xs:element name="last" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="email" type="email" />
                            <xs:element name="account">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="username" type="xs:string" />
                                        <xs:element name="password" type="xs:token" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="role" type="userRole" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="userId">
        <xs:restriction base="xs:token">
            <xs:pattern value="[0-9]{5}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="email">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="userRole">
        <xs:restriction base="xs:string">
            <xs:enumeration value="admin" />
            <xs:enumeration value="user" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Suong-Tran/HTTP-5203-Assignment2-SuongTran/users.xml
<?xml version="1.0" encoding="utf-8" ?>

<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user role="admin">
        <id>001</id>
        <name>
            <first>Juan</first>
            <middle>H.</middle>
            <last>Kim</last>
        </name>
        <email>sample@sample.com</email>
        <account>
            <username>jhkim112</username>
            <password>15E2B0D3C33891EBB0F1EF609EC419420C20E320CE94C65FBC8C3312448EB225</password>
        </account>
    </user>
    <user role="user">
        <id>002</id>
        <name>
            <first>John</first>
            <middle>Huan</middle>
            <last>Kopp</last>
        </name>
        <email>sample@sample.com</email>
        <account>
            <username>jhkopp65</username>
            <password>8A9BCF1E51E812D0AF8465A8DBCC9F741064BF0AF3B3D08E6B0246437C19F7FB</password>
        </account>
    </user>
</users>

=== Suong-Tran/HTTP-5203-Assignment2-SuongTran/xml/users.xml
<?xml version="1.0" encoding="utf-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/users.xsd">
    <user role="admin">
        <id>00001</id>
        <name>
            <first>Juan</first>
            <middle>H.</middle>
            <last>Kim</last>
        </name>
        <email>sample@sample.com</email>
        <account>
            <username>jhkim112</username>
            <password>$2y$10$d.O603MP5dg4rade7F29/.mCwxs3aOyWteLAFkESFw4RMbRlMmFPC</password>
        </account>
    </user>
    <user role="user">
        <id>00002</id>
        <name>
            <first>John</first>
            <middle>Huan</middle>
            <last>Kopp</last>
        </name>
        <email>sample@sample.com</email>
        <account>
            <username>jhkopp65</username>
            <password>$2y$10$tRSLNKON4cMftTb79GYLve7vc/L/MBshejmke8kyolpps3KrQNWAW</password>
        </account>
    </user>
    <user role="user">
        <id>00003</id>
        <name>
            <first>Mister</first>
            <middle>Gentle</middle>
            <last>Man</last>
        </name>
        <email>sample@sample.com</email>
        <account>
            <username>mistergentle</username>
            <password>$2y$10$roWOERrPAx6UKG/YqfYivOLmpPhG5SGB3Um9grrW.5dnSJdQxymuK</password>
        </account>
    </user>
</users>
